Python to Oracle SQL ORM
StasDzundza/python-to-oraclesql-orm pull request #5
Opened 2020-12-09 00:19 UTC by StasDzundza

**Додаткові завдання**
Кметь:
- база даних на Azure
- базовий клас Model для викликів методів (save/delete)_(class/object) з класу/об'єкту

Дзундза:
- Автоматична загрузка пакету на PyPi при мержі пул реквеста в мастер або при створенні релізу за допомогою GitHub CI. (Працездатність перевірена, https://github.com/StasDzundza/python-to-oraclesql-orm/actions/runs/419558372)

2020-12-11 12:49 UTC, hoherchak requested changes
Додайте перелік виконаних додаткових завдань і хто їх виконав в коментарі до PR.

2020-12-11 12:49 UTC, hoherchak commented on OracleSqlORM/.idea/modules.xml
> +<project version="4">
Приберіть .idea з гілки.

2020-12-11 19:58 UTC, StasDzundza commented on OracleSqlORM/.idea/modules.xml
> +<project version="4">
Прибрав

2020-12-11 23:09 UTC, hoherchak requested changes
Вкажіть більш конкретно який клієнт встановлювати.
```
Traceback (most recent call last):
  File "C:/Users/hoherchak/Downloads/Telegram Desktop/example.py", line 26, in <module>
    orm = Py2SQL()
  File "F:\YouTube\competitions\data_analysis_2020\parse_weather\venv\lib\site-packages\py_2_oracle_sql_orm\py2sql.py", line 28, in __init__
    cx_Oracle.init_oracle_client(lib_dir=oracle_client_dir)
cx_Oracle.DatabaseError: DPI-1072: the Oracle Client library version is unsupported
```

2020-12-12 12:45 UTC, StasDzundza commented
> Вкажіть більш конкретно який клієнт встановлювати.
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/hoherchak/Downloads/Telegram Desktop/example.py", line 26, in <module>
>     orm = Py2SQL()
>   File "F:\YouTube\competitions\data_analysis_2020\parse_weather\venv\lib\site-packages\py_2_oracle_sql_orm\py2sql.py", line 28, in __init__
>     cx_Oracle.init_oracle_client(lib_dir=oracle_client_dir)
> cx_Oracle.DatabaseError: DPI-1072: the Oracle Client library version is unsupported
> ```

 Для mac os(intel x86) потрібно завантажити архів за посиланням(https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.zip) розпакувати його та встановити змінну середовища ORACLE_CLIENT, яка буде вказувати на директорію 
path/to/instantclient_19_8

2020-12-14 08:34 UTC, hoherchak approved these changes

2020-12-15 09:02 UTC, merged